#!/bin/sh
# Univention SSL
#  fetch certificate from DC master
#
# Copyright 2019 Univention GmbH
#
# https://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <https://www.gnu.org/licenses/>.

if [ ! -x "/usr/sbin/univention-scp" ]; then
	echo "Couldn't download host certificate, univention-scp was not found"
	exit 1
fi

hostname="$1"
dcname="$2"
domainname="$(ucr get domainname)"

echo -n "Download host certificate: "
hostpwd="/etc/machine.secret"
hostaccount="$hostname\$"
counter=0
while true
do
	counter=$((counter+1))
	univention-scp "$hostpwd" -q -r \
		"$hostaccount@$dcname:/etc/univention/ssl/$hostname" \
		"$hostaccount@$dcname:/etc/univention/ssl/$hostname.$domainname" \
		"$hostaccount@$dcname:/etc/univention/ssl/\*.$hostname" \
		"$hostaccount@$dcname:/etc/univention/ssl/\*.$hostname.$domainname" \
		/etc/univention/ssl/ 2>&1
	[ -d "/etc/univention/ssl/$hostname" ] && [ -d "/etc/univention/ssl/$hostname.$domainname" ] \
		&& [ -d "/etc/univention/ssl/*.$hostname" ] && [ -d "/etc/univention/ssl/*.$hostname.$domainname" ] \
		&& break

	if [ $counter -gt 30 ] \
		&& [ ! -d "/etc/univention/ssl/$hostname" ] && [ ! -d "/etc/univention/ssl/$hostname.$domainname" ] \
		&& [ -d "/etc/univention/ssl/*.$hostname" ] && [ -d "/etc/univention/ssl/*.$hostname.$domainname" ]; then
		echo "failed to get host certificate"
		exit 1
	fi

	echo -n "."
	sleep 20
done

exit 0
